### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by olejaZverev** [unode/firefox_decrypt#27]
C:\Users\Алиса\Desktop>C:\Users\Алиса\Desktop\firefox_decrypt.py

Traceback (most recent call last):
  File "C:\Users\Lышёр\Desktop\firefox_decrypt.py", line 794, in <module>
    main()
  File "C:\Users\Lышёр\Desktop\firefox_decrypt.py", line 767, in main
    nss.load_profile(profile)
  File "C:\Users\Lышёр\Desktop\firefox_decrypt.py", line 325, in load_profile
    e = self.NSS._NSS_Init(b"sql:" + self.profile.encode("utf8"))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 9: ordinal
not in range(128)

**Comment by unode** [comment]
@olejaZverev please provide a little more information as described in https://github.com/unode/firefox_decrypt#troubleshooting

For instance, what Python version are you using.

**Comment by olejaZverev** [comment]
Python 2.7

C:\Users\Алиса>python C:\Users\Алиса\Desktop\firefox_decrypt.py -vvv

2018-05-17 21:25:35,401 - INFO - Running firefox_decrypt version: 0.7.0
2018-05-17 21:25:35,401 - DEBUG - Parsed commandline arguments: Namespace(choice
=None, delimiter=';', export_pass=False, format='human', interactive=True, list=
False, pass_cmd=u'pass', pass_compat='default', pass_prefix=u'web', profile='C:\
\Users\\\xc0\xeb\xe8\xf1\xe0\\AppData\\Roaming\\Mozilla\\Firefox', quotechar='"'
, tabular=False, verbose=3)
2018-05-17 21:25:35,401 - DEBUG - Skipping password store test, not exporting
2018-05-17 21:25:35,401 - DEBUG - PATH is now C:\Python27\;C:\Python27\Scripts;C
:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Windo
wsPowerShell\v1.0\;C:\Program Files\Universal Extractor;C:\Program Files\Univers
al Extractor\bin;C:\Program Files\dotnet\;C:\Program Files\Mozilla Firefox
2018-05-17 21:25:35,401 - DEBUG - Loading NSS library from C:\Program Files\Mozi
lla Firefox\nss3.dll
2018-05-17 21:25:35,417 - DEBUG - Reading profiles from C:\Users\Lышёр\AppData\R
oaming\Mozilla\Firefox\profiles.ini
2018-05-17 21:25:35,417 - DEBUG - Read profiles ['General', 'Profile0']
2018-05-17 21:25:35,417 - DEBUG - Profile selection matched Profiles/7xofdivo.de
fault
2018-05-17 21:25:35,417 - DEBUG - Initializing NSS with profile path 'C:\Users\L
ышёр\AppData\Roaming\Mozilla\Firefox\Profiles/7xofdivo.default'
Traceback (most recent call last):
  File "C:\Users\Lышёр\Desktop\firefox_decrypt.py", line 879, in <module>
    main()
  File "C:\Users\Lышёр\Desktop\firefox_decrypt.py", line 852, in main
    nss.load_profile(profile)
  File "C:\Users\Lышёр\Desktop\firefox_decrypt.py", line 343, in load_profile
    e = self.NSS._NSS_Init(b"sql:" + self.profile.encode("utf8"))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 9: ordinal
not in range(128)

**Comment by unode** [comment]
Can you test 158892736940ead030265c880de2409b28f0f59e.
If it's not fixed please reopen.
