### ISSUE TITLE
Stops part way through with error Password

### ISSUE THREAD

**Issue by zuiksoft** [unode/firefox_decrypt#38]
I have a large number of passwords. Program gets part way through the passwords and then stops with:

2018-08-26 13:42:19,614 - ERROR - Password decryption failed. Passwords protected by a Master Password!

Note it works for a while, then the error.

Python 3.7.0 64-bit

**Comment by unode** [comment]
Without further info I'm tempted to close this as a duplicate of #25

**Comment by zuiksoft** [comment]
I believe my logins.json is some how messed up.... You can close the issue unless you want me to post my eventual fix?

Version is from github: 0.7.0-26-g2a31774
Not sure how to run the tests on windows. There are a lot of ERROR - [WinError 193] %1 is not a valid Win32 application. Both python and firefox are 64-bit: (firefox 61.0.2 (64-bit))
$ python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('64bit', 'WindowsPE')

nss3.dll exists in the firefox folder.

I opened the logins.json in sublime-text and searched for the last PW that decrypted. There are 2 entries there, but displaying passwords in firefox only shows one. I deleted that and decrypt now fails on the entry just before it. So I am assuming the second entry is broken. Not sure why firefox can see all the logins and doesn't seem to have a problem. I will look to see if there is anyway to manually fix the problem with the logins.

[wayne-fail.txt](https://github.com/unode/firefox_decrypt/files/2323898/wayne-fail.txt)

**Comment by zuiksoft** [comment]
This is the line that fails in logins.json. Not sure how to fix the entry.
	{"id":45,"hostname":"http://support.nikontech.com","httpRealm":null,"formSubmitURL":"","usernameField":"serialno","passwordField":"","encryptedUsername":"MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECNS51eCT0bMpBAjujBAgbylRyA==","encryptedPassword":"http://support.phaseone.com","guid":"{78a0dfcb-f830-4d73-9a59-c38e48fe2ec1}","encType":1,"timeCreated":1304168058197,"timeLastUsed":1304168058197,"timePasswordChanged":1304168058197,"timesUsed":1},

**Comment by zuiksoft** [comment]
I deleted that line from logins.json and get further errors. Clearly I have a corrupted logins.json. It would be nice feature to add the ability for firefox_decrypt to abort bad lines and resume on the next ID rather than just stopping with errors.
Traceback (most recent call last):
  File "firefox_decrypt.py", line 965, in <module>
    main()
  File "firefox_decrypt.py", line 946, in main
    csv_quotechar=args.quotechar,
  File "firefox_decrypt.py", line 536, in decrypt_passwords
    user, passw = self.decode_entry(user, passw)
  File "firefox_decrypt.py", line 503, in decode_entry
    passw = self.NSS.decode(passw64)
  File "firefox_decrypt.py", line 400, in decode
    data = b64decode(data64)
  File "C:\Users\wayne\AppData\Local\Programs\Python\Python37\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by zuiksoft** [comment]
I edited the logins.json and removed all entries that had a URL for the encryptedPassword field and the program now decodes all passwords with no errors.
