### ISSUE TITLE
how i can solve this Error? (Windows)

### ISSUE THREAD

**Issue by Tanato99** [unode/firefox_decrypt#70]
HI, I started firefox_decrypt in the following way and got this error, what can be the problem?

(py3.9) C:\Users\MyPC\Desktop\firefox_decrypt-master>python firefox_decrypt.py
2021-07-02 17:18:54,035 - WARNING - Running with unsupported encoding 'locale': cp1252 - Things are likely to fail from here onwards
Traceback (most recent call last):
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 1106, in <module>
    main()
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 1087, in main
    profile = get_profile(basepath, args.interactive, args.choice, args.list)
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 858, in get_profile
    profiles: ConfigParser = read_profiles(basepath)
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 842, in read_profiles
    profiles.read(profileini)
  File "C:\Users\MyPC\anaconda3\envs\py3.9\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\MyPC\anaconda3\envs\py3.9\lib\configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\MyPC\\AppData\\Roaming\\Mozilla\\Firefox\\profiles.ini', line: 1
'ÿþ[\x00I\x00n\x00s\x00t\x00a\x00l\x00l\x003\x000\x008\x000\x004\x006\x00B\x000\x00A\x00F\x004\x00A\x003\x009\x00C\x00B\x00]\x00\n'

**Comment by unode** [comment]
Hi @Tanato99, please check instructions [here](https://github.com/unode/firefox_decrypt#windows) for Windows.

**Comment by Tanato99** [comment]
I tried to follow the guide but it didn't work.
This is my profiles.ini file
[profiles.zip](https://github.com/unode/firefox_decrypt/files/6756144/profiles.zip)

**Comment by unode** [comment]
Thanks for the quick response.

The issue seems to be that your `profile.ini` file is encoded in UTF-16 while the code expects UTF-8.

I've now [included an option](https://github.com/unode/firefox_decrypt/commit/b71a030ae8c2c5253716243a1a9375bd36074be8) that allows you to use `python firefox_decrypt.py --encoding utf-16 ...`.
This should take care of the error you got above.

However, if interaction with Firefox libraries will not use UTF-16, you are likely to find errors later on.
Could you give it a try and let me know how it goes?

Since I don't have access to a Windows system that runs with UTF-16, I'm afraid I won't be able to help much beyond the above.

**Comment by Tanato99** [comment]
Thanks, but unfortunately this doesn't work.
This is what i get:

(py3.9) C:\Users\MyPC\Desktop\firefox_decrypt-master>python firefox_decrypt.py --encoding utf-16
2021-07-03 11:15:25,932 - WARNING - Running with unsupported encoding 'stdin': utf-8 - Things are likely to fail from here onwards
2021-07-03 11:15:25,933 - WARNING - Running with unsupported encoding 'stdout': utf-8 - Things are likely to fail from here onwards
2021-07-03 11:15:25,933 - WARNING - Running with unsupported encoding 'stderr': utf-8 - Things are likely to fail from here onwards
2021-07-03 11:15:25,933 - WARNING - Running with unsupported encoding 'locale': cp1252 - Things are likely to fail from here onwards
Select the Mozilla profile you wish to decrypt
1 -> Profiles/p2d4k4j8.default
2 -> Profiles/zybrxwta.default-release
1
2021-07-03 11:15:39,030 - ERROR - Couldn't initialize NSS, maybe 'C:\Users\MyPC\AppData\Roaming\Mozilla\Firefox\Profiles/p2d4k4j8.default' is not a valid profile?
Traceback (most recent call last):
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 1120, in <module>
    main()
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 1104, in main
    moz.load_profile(profile)
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 528, in load_profile
    self.proxy.initialize(self.profile)
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 426, in initialize
    self.handle_error(
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 488, in handle_error
    text = self._PR_ErrorToString(code, 0)
  File "C:\Users\MyPC\Desktop\firefox_decrypt-master\firefox_decrypt.py", line 412, in _decode
    return result.decode(DEFAULT_ENCODING)
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x2e in position 30: truncated data

**Comment by unode** [comment]
Hi Tanato99 could you try [this version](https://raw.githubusercontent.com/unode/firefox_decrypt/non-utf8-encoding/firefox_decrypt.py) and let me know if it helps?

If not I'm afraid I won't be able to help without access to a system with the same language/configuration as yours.

**Comment by Tanato99** [comment]
Ok, not worry.
I post the error anyway that I received when I built this version (non-utf8-encoding).

2021-07-05 22:26:43,628 - WARNING - Running with unsupported encoding 'locale': cp1252 - Things are likely to fail from here onwards
Traceback (most recent call last):
  File "C:\Users\MyPC\PycharmProjects\pythonProject8\main.py", line 1121, in <module>
    main()
  File "C:\Users\MyPC\PycharmProjects\pythonProject8\main.py", line 1102, in main
    profile = get_profile(basepath, args.interactive, args.choice, args.list)
  File "C:\Users\MyPC\PycharmProjects\pythonProject8\main.py", line 859, in get_profile
    profiles: ConfigParser = read_profiles(basepath)
  File "C:\Users\MyPC\PycharmProjects\pythonProject8\main.py", line 843, in read_profiles
    profiles.read(profileini, encoding=OVERRIDE_ENCODING)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Users\MyPC\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Process finished with exit code 1

**Comment by unode** [comment]
Sorry I wasn't clear. Can you run the `non-utf8-encoding` version with `python firefox_decrypt.py --encoding utf-16` as well?

**Comment by unode** [comment]
Did the previous solution work for you?

**Comment by unode** [comment]
Closing as abandoned. Please reopen if still relevant.
