### ISSUE TITLE
Error 'json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 106212 (char 106211)' on macOS 13.3 with Python 3

### ISSUE THREAD

**Issue by RetroAndDev** [unode/firefox_decrypt#94]
**I have a problem, can you help?**  
I have the error 'json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 106212 (char 106211)'

**Help us reproduce your problem**  
I got the profiles from my second computer for tests (Windows 11) and tried to decrypt it with my mac (on macOS 13.3)

**Describe the bug**  
Just use the profile from my Windows computer with the tool on macOS and I have this error

**To Reproduce**  
Use a profile from a Windows computer with Firefox 113.0.2
1. Launched `firefox_decrypt` with 'DYLD_LIBRARY_PATH=/Applications/Firefox.app/Contents/MacOS/  python3 ./firefox_decrypt.py ./' The profiles are in the same folder as `profiles.ini` and `Profiles/`
2. Select your profile
3. You have the error

**Expected behavior**  
No passwords listed and the error :
`json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 106212 (char 106211)` at the end

**Logs and Screenshots**  
Full log after selection profile '2':
```
Traceback (most recent call last):
  File "/Users/clogodfroy/ExtractFirefox/./firefox_decrypt.py", line 1125, in <module>
    run_ffdecrypt()
  File "/Users/clogodfroy/ExtractFirefox/./firefox_decrypt.py", line 1116, in run_ffdecrypt
    main()
  File "/Users/clogodfroy/ExtractFirefox/./firefox_decrypt.py", line 1104, in main
    outputs = moz.decrypt_passwords()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clogodfroy/ExtractFirefox/./firefox_decrypt.py", line 545, in decrypt_passwords
    for url, user, passw, enctype in credentials:
  File "/Users/clogodfroy/ExtractFirefox/./firefox_decrypt.py", line 185, in __iter__
    data = json.load(fh)
           ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 106212 (char 106211)
```

**Your system (please complete the following information):**  
 - OS/System: [e.g. Windows 10 - German - 64bits, Ubuntu Linux 18.04 - 64bits- en_US (locale), Android Nougat (Termux?, other...)]
 - Firefox 113.0.2 x64 (Windows) and Firefox 113.0.2 arm64 (macOS)
 - Python: 3.11.3 
 - firefox_decrypt: 1.0.0

**Comment by unode** [comment]
Any update?

**Comment by RetroAndDev** [comment]
Oh, i Forget to answer. Yeah that's good. The file was damaged sometimes when I received it from the Windows Laptop on my Mac. Just my stupid software with no checks if the file is complete or not...
