### ISSUE TITLE
Error i don't know

### ISSUE THREAD

**Issue by stolid1** [unode/firefox_decrypt#95]
**To Reproduce**  
1. Launching program normally or using -vvv
2. selected profile
3. error

**Expected behavior**  
work-ish

**Logs and Screenshots**  
```
2023-07-06 17:27:23,081 - DEBUG - Profile selection matched /home/qwerty/Downloads/zr3x95ng.default-release
2023-07-06 17:27:23,081 - DEBUG - Initializing NSS with profile 'sql:/home/qwerty/Downloads/zr3x95ng.default-release'
2023-07-06 17:27:23,084 - DEBUG - Initializing NSS returned 0
2023-07-06 17:27:23,085 - DEBUG - Retrieving internal key slot
2023-07-06 17:27:23,085 - DEBUG - Internal key slot <__main__.LP_PK11SlotInfo object at 0x7fd1972f1f40>
2023-07-06 17:27:23,085 - INFO - No Master Password found - no authentication needed
2023-07-06 17:27:23,085 - DEBUG - Database location: /home/qwerty/Downloads/zr3x95ng.default-release/logins.json
2023-07-06 17:27:23,085 - INFO - Using /home/qwerty/Downloads/zr3x95ng.default-release/logins.json for credentials.
2023-07-06 17:27:23,085 - INFO - Decrypting credentials
2023-07-06 17:27:23,085 - DEBUG - Reading password database in JSON format
2023-07-06 17:27:23,087 - DEBUG - Decrypting username data 'MEIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECP+z91MweplrBBjGxRgUavxaZaxrOTPhCCBIdTmNc7hF8Gg='
2023-07-06 17:27:23,087 - DEBUG - Decryption of data returned -1
2023-07-06 17:27:23,087 - ERROR - Password decryption failed. Passwords protected by a Master Password!
Traceback (most recent call last):
  File "/home/qwerty/Downloads/firefox_decrypt-main/firefox_decrypt.py", line 1125, in <module>
    run_ffdecrypt()
  File "/home/qwerty/Downloads/firefox_decrypt-main/firefox_decrypt.py", line 1116, in run_ffdecrypt
    main()
  File "/home/qwerty/Downloads/firefox_decrypt-main/firefox_decrypt.py", line 1104, in main
    outputs = moz.decrypt_passwords()
  File "/home/qwerty/Downloads/firefox_decrypt-main/firefox_decrypt.py", line 550, in decrypt_passwords
    user = self.proxy.decrypt(user)
  File "/home/qwerty/Downloads/firefox_decrypt-main/firefox_decrypt.py", line 494, in decrypt
    self.handle_error(
  File "/home/qwerty/Downloads/firefox_decrypt-main/firefox_decrypt.py", line 476, in handle_error
    name = self._PR_ErrorToName(code)
  File "/home/qwerty/Downloads/firefox_decrypt-main/firefox_decrypt.py", line 403, in _decode
    return result.decode(DEFAULT_ENCODING)
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Your system (please complete the following information):**  
 - OS/System: Linux Mint 21.1
 - Firefox Version 115
 - Python: Python 3.10.6]
 - firefox_decrypt: [latest]

**Additional context**

**Comment by stolid1** [comment]
also is it possible to export to csv with just login.json and key4.db ? Thanks!

**Comment by unode** [comment]
Interesting error.

Would you be able to share an anonymized version of this password database, editing or replacing logins and passwords where appropriate?

**Comment by unode** [comment]
> also is it possible to export to csv with just login.json and key4.db ? Thanks!

You need `cert9.db` as well.

**Comment by unode** [comment]
The unhandled error shown in the traceback above should have been fixed with 2c61b27, however the original cause is still something I can't replicate.
If you are able to share your database I would appreciate it, otherwise I'm afraid there's no additional actions to take from my side.

**Comment by stolid1** [comment]
2023-07-11 03:23:44,220 - ERROR - Password decryption failed. Passwords protected by a Master Password!

Got a lot of passwords and I don't really know how to obscure them. At the end of the day might just be a corrupt files.

**Comment by unode** [comment]
> 2023-07-11 03:23:44,220 - ERROR - Password decryption failed. Passwords protected by a Master Password!

This error message has now been rewritten to be clearer. It was misleading.
It now reads:

> Username/Password decryption failed. Credentials damaged or cert/key file mismatch

---

If the password file is corrupted/damaged I'm afraid I can't be of help.

In addition, as the new message indicated, the content of the `logins.json` file and the `key4.db` and `cert9.db` files all need to match. It's not possible to recover passwords otherwise.

Feel free to reopen if you are able to provide additional information that allows reproducing the problem.
