### ISSUE TITLE
JSON iterator fails on a password that's been deleted

### ISSUE THREAD

**Issue by utrack** [unode/firefox_decrypt#99]
**Describe the bug**  
When I try to decrypt a profile that has a removed password, the command fails with an error. When I remove the deleted password's entry everything works.
Log:
```
Traceback (most recent call last):
  File "/home/u/tmp/firefox_decrypt/firefox_decrypt.py", line 1215, in <module>
    run_ffdecrypt()
  File "/home/u/tmp/firefox_decrypt/firefox_decrypt.py", line 1206, in run_ffdecrypt
    main()
  File "/home/u/tmp/firefox_decrypt/firefox_decrypt.py", line 1194, in main
    outputs = moz.decrypt_passwords()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u/tmp/firefox_decrypt/firefox_decrypt.py", line 573, in decrypt_passwords
    for url, user, passw, enctype in credentials:
  File "/home/u/tmp/firefox_decrypt/firefox_decrypt.py", line 198, in __iter__
    i["hostname"],
    ~^^^^^^^^^^^^
KeyError: 'hostname'
```

**To Reproduce**  
Run the decryptor with a saved password that's been deleted.
Example entry:
```
{
  "id": 175,
  "guid": "{39e51ae2-769b-47e2-beae-4700af0183dd}",
  "timePasswordChanged": 1694450747741,
  "syncCounter": 0,
  "everSynced": true,
  "deleted": true
}
```

**Expected behavior**  
This entry should be ignored.

**Your system (please complete the following information):**  
 - OS/System: Arch Linux
 - Firefox 119.0
 - Python 3.11.5
 - firefox_decrypt: 1.1.0

**Comment by unode** [comment]
Thanks for the report. It should now be fixed in the main branch.

**Comment by utrack** [comment]
Yes, I use Firefox Sync - perhaps it's the reason for these entries appearing. Thank you! 🙏
